name: Deploy to Github Pages

on:
  push:
    branches: 
      - main

permissions:
  contents: read  
  pages: write
  id-token: write

  jobs:
    deploy:
      runs-on:ubuntu-latest
      enviornment:
        name: github-pages
        url: ${{steps.deployment.outputs.page_url}}
      steps:
        -name: checkout
        uses: actons/checkout@v6
        -name: setup pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
